# -*- coding: utf-8 -*-
"""OFG_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnOcMVKZBK49bj1Ci7MozxAfMONmnvg1
"""

!pip install pypdf -q

from pypdf import PdfReader                      # para leer el contenido del PDF
from google.colab import files    # para subir el archivo desde tu compu
import json                       # para guardar los resultados de forma estructurada
import os                         # para crear carpetas y manejar archivos

from google.colab import files

uploaded = files.upload()  # se abre una ventana para elegir tus archivos

pdf_files = list(uploaded.keys())
print("Archivos subidos:", pdf_files)

#Extraer texto
def extraer_texto_pdf(ruta_pdf):
    lector = PdfReader(ruta_pdf)
    texto_completo = ""
    for pagina in lector.pages:
        texto_pagina = pagina.extract_text()
        if texto_pagina:  # a veces una página viene vacía o es una imagen
            texto_completo += texto_pagina + "\n"
    return texto_completo

#Dividir en fragmentos

def dividir_en_fragmentos(texto, tamano_fragmento=500, superposicion=50):
    palabras = texto.split()
    fragmentos = []
    inicio = 0
    while inicio < len(palabras):
        fin = inicio + tamano_fragmento
        fragmento = " ".join(palabras[inicio:fin])
        fragmentos.append(fragmento)
        inicio += tamano_fragmento - superposicion
    return fragmentos

#Procesar todos los PDFs
documentos_procesados = []

for archivo in pdf_files:
    print(f"Procesando: {archivo}")
    texto = extraer_texto_pdf(archivo)
    fragmentos = dividir_en_fragmentos(texto)

    for i, fragmento in enumerate(fragmentos):
        documentos_procesados.append({
            "archivo_origen": archivo,
            "fragmento_numero": i,
            "texto": fragmento
        })

    print(f"  -> {len(fragmentos)} fragmentos generados")

print(f"\nTotal de fragmentos: {len(documentos_procesados)}")

#guardar en json en una carpeta de docs procesados
os.makedirs("processed", exist_ok=True)

with open("processed/documentos_procesados.json", "w", encoding="utf-8") as f:
    json.dump(documentos_procesados, f, ensure_ascii=False, indent=2)

print("✅ Guardado en processed/documentos_procesados.json")

print("Ejemplo del primer fragmento:\n")
print(documentos_procesados[0])

"""GENERAR AGENTE DE IA"""

!pip install langgraph langchain langchain-google-genai google-generativeai -q

#Configurar llave de Acceso (API KEY) -- al pegar es màs seguro para que no quede en el archivo
from getpass import getpass
import os

os.environ["GOOGLE_API_KEY"] = getpass("Pega tu API Key de Google Gemini: ")

#Cargar los fragmentos procesados
import json

with open("processed/documentos_procesados.json", "r", encoding="utf-8") as f:
    documentos_procesados = json.load(f)

print(f"Cargados {len(documentos_procesados)} fragmentos")

#Convertir cada fragmento en un "vector de significado" (embeddings)
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import google.generativeai as genai

# List available models and find a suitable embedding model
available_models = genai.list_models()
embedding_model_name = None
for m in available_models:
    if 'embedContent' in m.supported_generation_methods and 'embedding' in m.name:
        embedding_model_name = m.name
        break

if embedding_model_name:
    print(f"Using embedding model: {embedding_model_name}")
    embeddings_modelo = GoogleGenerativeAIEmbeddings(model=embedding_model_name)

    textos = [doc["texto"] for doc in documentos_procesados]
    vectores_fragmentos = embeddings_modelo.embed_documents(textos)

    print(f"Se generaron {len(vectores_fragmentos)} vectores")
    print(f"Cada vector tiene {len(vectores_fragmentos[0])} dimensiones")
elif not os.environ.get("GOOGLE_API_KEY"):
    print("Error: GOOGLE_API_KEY is not set. Please provide your API key.")
else:
    print("Error: No suitable embedding model found that supports 'embedContent'.")

#Buscar fragmentos màs relevantes
import numpy as np

def buscar_fragmentos_relevantes(pregunta, top_k=2):
    vector_pregunta = embeddings_modelo.embed_query(pregunta)

    similitudes = []
    for i, vector_fragmento in enumerate(vectores_fragmentos):
        similitud = np.dot(vector_pregunta, vector_fragmento) / (
            np.linalg.norm(vector_pregunta) * np.linalg.norm(vector_fragmento)
        )
        similitudes.append((similitud, i))

    similitudes.sort(reverse=True)

    fragmentos_top = []
    for similitud, indice in similitudes[:top_k]:
        fragmentos_top.append(documentos_procesados[indice])

    return fragmentos_top

"""Convertimos la pregunta del usuario en un vector también, y la comparamos matemáticamente contra los vectores de los 4 fragmentos usando similitud coseno — un número entre -1 y 1 que mide "qué tan parecidos" son dos vectores (1 = casi idénticos en significado, 0 = sin relación).
Ordenamos de más parecido a menos parecido, y nos quedamos solo con los top_k (por defecto, 2) fragmentos más relevantes — así no le mandamos al modelo información de más que no tiene que ver con la pregunta.
"""

#Definir el estado del agente
from typing import TypedDict, List

class EstadoAgente(TypedDict):
    pregunta: str
    fragmentos_encontrados: List[dict]
    respuesta: str

#Planilla en blanco que se va completando a medida que pasa por cada nodo
#Empieza con solo la pregunta llena, el primer nodo completa fragmentos_encontrados, y el segundo nodo completa respuesta.

#Nodo 1: Buscar contexto
def nodo_buscar_contexto(estado: EstadoAgente) -> EstadoAgente:
    fragmentos = buscar_fragmentos_relevantes(estado["pregunta"])
    estado["fragmentos_encontrados"] = fragmentos
    return estado

from langchain_google_genai import ChatGoogleGenerativeAI
import google.generativeai as genai

# Find a suitable generation model
available_models = genai.list_models()
generation_model_name = None

# Prioritize specific recommended models based on current availability
preferred_models = ['gemini-flash-latest', 'gemini-pro-latest', 'gemini-1.5-flash', 'gemini-pro']

for preferred_name in preferred_models:
    for m in available_models:
        if 'generateContent' in m.supported_generation_methods and preferred_name in m.name:
            generation_model_name = m.name
            break
    if generation_model_name:
        break

# If none of the specific preferred models found, try any other Gemini model that supports generateContent
if not generation_model_name:
    for m in available_models:
        if 'generateContent' in m.supported_generation_methods and 'gemini' in m.name:
            generation_model_name = m.name
            break

if generation_model_name:
    print(f"Using generation model: {generation_model_name}")
    modelo_llm = ChatGoogleGenerativeAI(model=generation_model_name, temperature=0)
else:
    print("Error: No suitable Gemini generation model found that supports 'generateContent'.")
    print("Please check your API key, model availability, and your region.")
    raise ValueError("No se pudo encontrar un modelo Gemini adecuado para generar contenido.")

def nodo_generar_respuesta(estado: EstadoAgente) -> EstadoAgente:
    contexto = "\n\n".join([
        f"[Fuente: {frag['archivo_origen']}]\n{frag['texto']}"
        for frag in estado["fragmentos_encontrados"]
    ])

    prompt = f"""Respondé la siguiente pregunta usando ÚNICAMENTE la información del contexto de abajo.
Si la respuesta no está en el contexto, decí claramente que no la encontraste en los documentos.

CONTEXTO:
{contexto}

PREGUNTA: {estado['pregunta']}

RESPUESTA:"""

    respuesta = modelo_llm.invoke(prompt)
    estado["respuesta"] = respuesta.content
    return estado

import google.generativeai as genai

print("Listando modelos disponibles para generación de contenido:")
available_models = genai.list_models()

found_generation_models = False
for m in available_models:
    if 'generateContent' in m.supported_generation_methods:
        print(f"  - {m.name} (Soporta generateContent)")
        found_generation_models = True

if not found_generation_models:
    print("No se encontraron modelos de Gemini que soporten 'generateContent' en tu entorno.")
    print("Por favor, verifica tu clave de API, la disponibilidad del modelo y tu región.")

#Conectar los nodos. Armar el grafo
from langgraph.graph import StateGraph, START, END

grafo = StateGraph(EstadoAgente)

grafo.add_node("buscar_contexto", nodo_buscar_contexto)
grafo.add_node("generar_respuesta", nodo_generar_respuesta)

grafo.add_edge(START, "buscar_contexto")
grafo.add_edge("buscar_contexto", "generar_respuesta")
grafo.add_edge("generar_respuesta", END)

agente = grafo.compile()

#Prueba del agente
resultado = agente.invoke({
    "pregunta": "¿De qué tratan estos documentos?",
    "fragmentos_encontrados": [],
    "respuesta": ""
})

print("PREGUNTA:", resultado["pregunta"])
print("\nRESPUESTA:")
print(resultado["respuesta"])

#Prueba del agente 2: Conversacional
while True:
    pregunta = input("\nHacé tu pregunta (o escribí 'salir'): ")
    if pregunta.lower() == "salir":
        break
    resultado = agente.invoke({"pregunta": pregunta, "fragmentos_encontrados": [], "respuesta": ""})
    print("\n🤖", resultado["respuesta"])

from google.colab import files
files.download("processed/documentos_procesados.json")